In [1008]:
import pandas as pd
import pymatreader as pmr
import numpy as np

In [1009]:
file_name='S44' #Указать номер человека#
data=pmr.read_mat(f'исходное/{file_name}.mat') #Указать путь к файлу#
df_not_clean=pd.DataFrame(data[file_name])

In [1010]:
useless_demographic=['Age', 'Gender', 'DominantHand', 'Education', 'MaritalStatus', 'Children']
useless_profile=['WeeklySupermarketVisits', 'SupermarketVisitDuration', 'PriceImpact', 'BrandImpact', 'DiscountImpact', 'AdvertisementImpact', 'SuggestionImpact', 'ShoppingList', 'VerbalVisual', 'Spontaneous', 'VarietySeeker', 'UtilitarianMotivation', 'HedonicMotivation', 'Extraversion', 'Neuroticism', 'Agreeableness', 'Openness', 'Conscientiousness', 'BargainHunter']

In [1011]:
df_not_clean.rename(index={
    'education': 'Education',
    'marital_status': 'MaritalStatus'
}, inplace=True)

In [1012]:
useless_products=np.arange(1, 25, 1)
s=[]
for i in useless_products:
    s.append('Product'+str(i))
useless_products=s

In [1013]:
et_useful_data=df_not_clean['ET_clean']
et_useful_data=et_useful_data.drop(useless_demographic+useless_profile+useless_products)
et_useful_data=pd.DataFrame(et_useful_data).transpose()

In [1014]:
et_data=et_useful_data.Data['ET_clean']
et_chans=et_useful_data.chans['ET_clean']

In [1015]:
df_products=df_not_clean.drop(columns=['Profile', 'Demographics', 'EEG_clean', 'ET_clean'])
df_products.drop(useless_demographic+useless_profile+['Data', 'Fs', 'chans'], inplace=True)
useless_pages=['Page1', 'Page2', 'Page3', 'Page4', 'Page5', 'Page6']
num_of_products=24

In [1016]:
df_et=pd.DataFrame()

In [1017]:
#Как-будто не работает#
for t in useless_pages:
    for q in range(24):
        prdct=df_products[t][q]
        et_vrem_seg=prdct['ET_segments']
        for i in et_vrem_seg:
            if isinstance(i, np.int32):
                et_vrem_seg=np.delete(et_vrem_seg, np.where(et_vrem_seg==i)) #?#

C:\Users\Егор\AppData\Local\Temp\ipykernel_6380\3104736383.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  prdct=df_products[t][q]


In [1018]:
prodct=df_products['Page1'][0]
product_info=prodct['ProductInfo']
et_prodct=prodct['ET_segments']

if len(et_prodct)==0:
    pass
else:
    for i in range(len(et_chans)):
        location=et_chans[i]
        et_i=et_data[i]
        et_i_for_prodct=[]
        
        if isinstance(et_prodct[0], np.ndarray):
            for j in et_prodct:
                s=[]
                for k in range(j[1]-j[0]):
                    s.append(et_i[j[0]+k])
                et_i_for_prodct.append(s)
        else:
            s=[]
            for k in range(et_prodct[1]-et_prodct[0]):
                s.append(et_i[et_prodct[0]+k])
            et_i_for_prodct.append(s)
        df_et[f'{location}']=[et_i_for_prodct]

df_et['info']=[product_info]

C:\Users\Егор\AppData\Local\Temp\ipykernel_6380\910173933.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  prodct=df_products['Page1'][0]


In [1019]:
for t in useless_pages:
    for q in range(1, num_of_products):

        dfvrem_et=pd.DataFrame()
        prodct=df_products[t][q]
        product_info=prodct['ProductInfo']
        et_prodct=prodct['ET_segments']

        print(et_prodct)

        if len(et_prodct)==0:
            pass
        else:
            for i in range(len(et_chans)):
                location=et_chans[i]
                et_i=et_data[i]
                et_i_for_prodct=[]
                
                if isinstance(et_prodct[0], np.ndarray):
                    for j in et_prodct:
                        s=[]
                        for k in range(j[1]-j[0]):
                            s.append(et_i[j[0]+k])
                        et_i_for_prodct.append(s)
                else:
                    s=[]
                    for k in range(et_prodct[1]-et_prodct[0]):
                        s.append(et_i[et_prodct[0]+k])
                    et_i_for_prodct.append(s)
                dfvrem_et[f'{location}']=[et_i_for_prodct]
            dfvrem_et['info']=[product_info]
            df_et=pd.concat([df_et, dfvrem_et], ignore_index=True)
df_et.reset_index(inplace=True)

C:\Users\Егор\AppData\Local\Temp\ipykernel_6380\1662568629.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  prodct=df_products[t][q]
C:\Users\Егор\AppData\Local\Temp\ipykernel_6380\1662568629.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  prodct=df_products[t][q]
C:\Users\Егор\AppData\Local\Temp\ipykernel_6380\1662568629.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  prodct=df_products[t][q]
C:\Users\Егор\AppData\Local\

[[18885 18887]
 [18942 19086]
 [19457 19458]
 [20112 20174]
 [23424 23425]]
[[18835 18840]
 [18842 18844]
 [18846 18862]
 [18991 19020]
 [19086 19087]
 [19163 19223]
 [19455 19456]
 [19513 19514]
 [20175 20217]]
[[19460 19488]
 [20051 20073]
 [20075 20077]
 [23477 23479]
 [23481 23614]]
[[18789 18790]
 [18794 18795]
 [18884 18885]
 [19459 19460]
 [19489 19510]]
[[18795 18843]
 [18846 18847]
 [18850 18856]
 [18858 18861]
 [18863 18884]
 [19512 19513]
 [21133 21135]]
[[20016 20050]
 [21891 22046]]
[[18762 18776]
 [18778 18781]
 [18783 18793]
 [21165 21185]
 [21382 21384]
 [21387 21388]
 [21391 21392]
 [21394 21395]
 [21396 21398]
 [21405 21406]
 [21858 21890]
 [22048 22049]]
[[18866 18867]
 [18868 18869]
 [18871 18872]
 [18873 18874]
 [18875 18876]
 [18878 18879]
 [18881 18882]
 [19681 19702]
 [21136 21164]
 [21186 21187]
 [21376 21431]
 [21811 21857]]
[[19970 20015]
 [21482 21483]
 [21486 21489]
 [21492 21493]
 [21494 21500]
 [21503 21504]
 [21505 21512]
 [21514 21515]
 [21518 21524]
 [

C:\Users\Егор\AppData\Local\Temp\ipykernel_6380\1662568629.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  prodct=df_products[t][q]
C:\Users\Егор\AppData\Local\Temp\ipykernel_6380\1662568629.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  prodct=df_products[t][q]
C:\Users\Егор\AppData\Local\Temp\ipykernel_6380\1662568629.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  prodct=df_products[t][q]
C:\Users\Егор\AppData\Local\

[[31378 31420]
 [32835 32836]
 [32984 32999]
 [33001 33037]
 [34112 34142]
 [34404 34434]
 [35882 35899]]
[[32551 32582]
 [33756 33853]
 [34627 34787]
 [34862 34884]
 [34945 35153]
 [35201 35317]
 [35420 35588]]
[[32468 32469]
 [32510 32550]
 [33699 33756]
 [33855 33973]
 [34010 34012]
 [34016 34017]
 [34018 34055]
 [34436 34438]
 [34463 34626]
 [34788 34789]
 [34794 34851]
 [34885 34945]
 [35154 35200]
 [35318 35407]
 [35590 35763]]
[[32469 32508]
 [34435 34436]
 [35776 35777]
 [35778 35781]
 [35791 35848]
 [35926 36021]]
[[32242 32244]
 [32583 32716]
 [34852 34853]]
[[32227 32262]
 [32427 32467]
 [32717 32718]
 [33655 33698]
 [33974 33975]
 [34002 34008]
 [34016 34017]
 [34439 34462]
 [34861 34862]]
[[32188 32226]
 [32262 32308]
 [32354 32426]
 [32718 32719]
 [33604 33653]
 [35764 35765]]
[[31466 31503]
 [31562 31587]
 [31628 31629]
 [31658 31660]]
[[31503 31561]
 [31587 31589]
 [31624 31625]
 [31701 31704]]
[[31590 31623]
 [33109 33193]]
[[31626 31627]
 [31629 31669]
 [32834 32835]


C:\Users\Егор\AppData\Local\Temp\ipykernel_6380\1662568629.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  prodct=df_products[t][q]
C:\Users\Егор\AppData\Local\Temp\ipykernel_6380\1662568629.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  prodct=df_products[t][q]
C:\Users\Егор\AppData\Local\Temp\ipykernel_6380\1662568629.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  prodct=df_products[t][q]
C:\Users\Егор\AppData\Local\

In [1020]:
df_et

index                                             left_x  \
0        0  [[0.19578932, 0.2021533, 0.19725941, 0.2009152...   
1        1  [[0.23339225, 0.20802774], [0.27457297, 0.2724...   
2        2  [[0.42508772, 0.42454258, 0.42774543, 0.425089...   
3        3  [[0.22150046, 0.21575053, 0.21275394, 0.211969...   
4        4  [[0.28236398], [0.4061389], [0.2628443], [0.21...   
..     ...                                                ...   
132    132  [[0.6580611, 0.6628908, 0.6644114, 0.658353, 0...   
133    133  [[0.76668155, 0.7667493, 0.76917946, 0.7696188...   
134    134  [[0.45112032, 0.3967449], [0.53184247, 0.51974...   
135    135  [[0.755996], [0.69195545, 0.6682456, 0.6505877...   
136    136  [[0.75034976, 0.7513977, 0.76124024, 0.7585457...   

                                                left_y  \
0    [[0.15096553, 0.1427856, 0.14859362, 0.1465732...   
1    [[0.19416139, 0.15326726], [0.14274284, 0.1720...   
2    [[0.2777737, 0.30092147, 0.31335968, 0.2728693...   
3    [[0.39166036, 0.40169945, 0.39550516, 0.398818...   
4    [[0.5335952], [0.44093314], [0.24331814], [0.4...   
..                                                 ...   
132  [[0.5776711, 0.5803392, 0.5757092, 0.57313985,...   
133  [[0.59024143, 0.5777231, 0.5839609, 0.5800396,...   
134  [[0.7966802, 0.8003112], [0.826953, 0.8164805,...   
135  [[0.82969385], [0.7970005, 0.802013, 0.7975147...   
136  [[0.82510656, 0.81963694, 0.8266013, 0.8246639...   

                                            left_pupil  \
0    [[2.7185059, 2.729477, 2.7384033, 2.737503, 2....   
1    [[2.7345123, 2.7384186], [2.840454, 2.8864746,...   
2    [[2.679306, 2.7056427, 2.7221985, 2.6566162, 2...   
3    [[3.0728912, 3.090744, 3.0687866, 3.0524902, 3...   
4    [[2.855667], [2.8549194], [2.6780396], [3.0428...   
..                                                 ...   
132  [[3.0278168, 3.0477142, 3.0364838, 3.0473328, ...   
133  [[3.0855255, 3.115036, 3.0985565, 3.0957336, 3...   
134  [[3.0414276, 3.042572], [2.9439697, 2.9358368,...   
135  [[3.006607], [3.0475006, 3.0473328, 3.0517883,...   
136  [[3.0339966, 3.0304565, 3.022705, 3.0235443, 3...   

                                               right_x  \
0    [[0.22691947, 0.22716221, 0.22899054, 0.223628...   
1    [[0.26302618, 0.23501608], [0.30668768, 0.2935...   
2    [[0.4665151, 0.46630982, 0.4669503, 0.46490276...   
3    [[0.24418534, 0.2321173, 0.23056567, 0.2323126...   
4    [[0.3023396], [0.44151106], [0.2916372], [0.23...   
..                                                 ...   
132  [[0.6819279, 0.68761873, 0.6889479, 0.68309444...   
133  [[0.78837126, 0.78551424, 0.7833488, 0.7887299...   
134  [[0.50494415, 0.4204353], [0.5756295, 0.561883...   
135  [[0.7701481], [0.7114045, 0.6818434, 0.6662679...   
136  [[0.77847385, 0.775657, 0.7787142, 0.7783664, ...   

                                               right_y  \
0    [[0.18227847, 0.1697132, 0.17198908, 0.1753164...   
1    [[0.21909879, 0.18247981], [0.18815808, 0.1924...   
2    [[0.36550835, 0.3395485, 0.37608227, 0.3609977...   
3    [[0.43886545, 0.41239268, 0.43012178, 0.432805...   
4    [[0.5425721], [0.38060686], [0.2868742], [0.44...   
..                                                 ...   
132  [[0.60559195, 0.5933982, 0.5904068, 0.61013806...   
133  [[0.6207281, 0.59979504, 0.60224557, 0.5916795...   
134  [[0.8047701, 0.8094584], [0.8587655, 0.8609647...   
135  [[0.84129065], [0.82894826, 0.83171004, 0.8380...   
136  [[0.84493375, 0.8493928, 0.85599506, 0.8512777...   

                                           right_pupil  \
0    [[2.8801422, 2.878067, 2.8668976, 2.8776855, 2...   
1    [[2.8397064, 2.8537445], [3.0197906, 3.0212708...   
2    [[2.8843231, 2.8025208, 2.8975983, 2.8411102, ...   
3    [[3.2732697, 3.2041473, 3.212616, 3.2281036, 3...   
4    [[2.9558563], [2.782959], [2.827896], [3.23555...   
..                                                 ...   
132  [[3.2099915, 3.1960297, 3

In [1021]:
df_et.to_csv(f'et_{file_name}.csv')